### ISSUE TITLE
Polkascan can't process block 188889 on Polkadot CC-1 due to "ProxyType" not found error

### ISSUE THREAD

**Issue by vshvsh** [polkascan/polkascan-os#22]
Processing fails on a block 188889 with error:
```
Processing 0xcaf3059a641b36e81635b3f427e7e49b96be2473f7f780e18823039b26ba25b7 ...
Metadata: CACHE MISS 5
[2020-06-09 04:11:39 +0000] [13] [ERROR] Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/falcon/api.py", line 244, in __call__
    responder(req, resp, **params)
  File "/usr/src/app/app/resources/harvester.py", line 179, in on_post
    block = harvester.add_block(block_hash)
  File "/usr/src/app/app/processors/converters.py", line 590, in add_block
    extrinsic_data = extrinsics_decoder.decode()
  File "/usr/src/app/py-scale-codec/scalecodec/base.py", line 278, in decode
    self.value = self.process()
  File "/usr/src/app/py-scale-codec/scalecodec/block.py", line 169, in process
    arg_type_obj = self.process_type(arg.type, metadata=self.metadata)
  File "/usr/src/app/py-scale-codec/scalecodec/base.py", line 358, in process_type
    obj = self.get_decoder_class(type_string, self.data, **kwargs)
  File "/usr/src/app/py-scale-codec/scalecodec/base.py", line 354, in get_decoder_class
    raise NotImplementedError('Decoder class for "{}" not found'.format(type_string))
NotImplementedError: Decoder class for "ProxyType" not found

Processing 0xcaf3059a641b36e81635b3f427e7e49b96be2473f7f780e18823039b26ba25b7 ...
Metadata: CACHE MISS 5
[2020-06-09 04:11:41 +0000] [13] [ERROR] Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/falcon/api.py", line 244, in __call__
    responder(req, resp, **params)
  File "/usr/src/app/app/resources/harvester.py", line 179, in on_post
    block = harvester.add_block(block_hash)
  File "/usr/src/app/app/processors/converters.py", line 590, in add_block
    extrinsic_data = extrinsics_decoder.decode()
  File "/usr/src/app/py-scale-codec/scalecodec/base.py", line 278, in decode
    self.value = self.process()
  File "/usr/src/app/py-scale-codec/scalecodec/block.py", line 169, in process
    arg_type_obj = self.process_type(arg.type, metadata=self.metadata)
  File "/usr/src/app/py-scale-codec/scalecodec/base.py", line 358, in process_type
    obj = self.get_decoder_class(type_string, self.data, **kwargs)
  File "/usr/src/app/py-scale-codec/scalecodec/base.py", line
```

It affects your public front-end too:
https://polkascan.io/polkadot-cc1

**Comment by arjanz** [comment]
This was due to a missing type introduced in the runtime upgrade last night, I just bumped the version of the scale-codec, a pull from master should resolve this issue

**Comment by vshvsh** [comment]
It did resolve the issue, thanks.
