### ISSUE TITLE
Deployed but no Data is visible

### ISSUE THREAD

**Issue by dillu24** [polkascan/polkascan-os#35]
I have deployed a full instance of the Kusama explorer, and it has been running for weeks now. However, no data could be displayed on the UI. I followed this guide https://medium.com/polkadot-network/polkascan-development-update-6-4c3fe8e80629. Did I miss something?

**Comment by dillu24** [comment]
Could it be there is something wrong with the database?

**Comment by emielvanderhoek** [comment]
@arjanz would you be so kind to follow-up when you find the time?

**Comment by dillu24** [comment]
Any news?

**Comment by huythanhcere** [comment]
Same to me. With V0.6.2, run docker-compose.yml follow the readme file. I found that worker have error so that there no data is saved to DB. Below is details error log. I guess due to sql session. Do you have any suggestion @arjanz 
[2021-02-05 08:01:39,744: INFO/MainProcess] Received task: app.tasks.start_harvester[4ecb6627-095c-4a15-a161-62c462c4c29a]  
[2021-02-05 08:01:39,795: INFO/MainProcess] Received task: app.tasks.start_sequencer[bbeafaa2-1900-41c2-8c9e-d38bb720f8d8]  
[2021-02-05 08:01:39,827: INFO/ForkPoolWorker-2] Task app.tasks.start_harvester[4ecb6627-095c-4a15-a161-62c462c4c29a] succeeded in 0.07237339999846881s: {'result': 'Harvester job started', 'block_sets': [{'start_block_hash': '0xac114aa803c4f4f8f5b36fbf27e67a04a9c54b1fad4e74e4d3173da51d8e1702', 'end_block_hash': None}], 'sequencer_task_id': 'bbeafaa2-1900-41c2-8c9e-d38bb720f8d8'}
[2021-02-05 08:01:39,862: INFO/MainProcess] Received task: app.tasks.accumulate_block_recursive[a8d745cf-63e9-4a60-b4b9-5d22bcd19bf7]  
[2021-02-05 08:01:39,896: WARNING/ForkPoolWorker-2] Init: create entrypoints
[2021-02-05 08:01:40,193: INFO/ForkPoolWorker-1] Task app.tasks.start_sequencer[bbeafaa2-1900-41c2-8c9e-d38bb720f8d8] succeeded in 0.3839516999978514s: {'result': 'Block #161 is missing.. stopping check '}
[2021-02-05 08:01:40,398: WARNING/ForkPoolWorker-2] Metadata: CACHE MISS
[2021-02-05 08:01:40,399: WARNING/ForkPoolWorker-2] 10
[2021-02-05 08:01:40,452: WARNING/ForkPoolWorker-2] store version to db
[2021-02-05 08:01:40,452: WARNING/ForkPoolWorker-2] MetadataV11Decoder
[2021-02-05 08:01:41,794: WARNING/ForkPoolWorker-2] Metadata: CACHE MISS
[2021-02-05 08:01:41,795: WARNING/ForkPoolWorker-2] 10
[2021-02-05 08:01:41,833: WARNING/ForkPoolWorker-2] ! ERROR adding 0xac114aa803c4f4f8f5b36fbf27e67a04a9c54b1fad4e74e4d3173da51d8e1702
[2021-02-05 08:01:41,835: ERROR/ForkPoolWorker-2] Task app.tasks.accumulate_block_recursive[a8d745cf-63e9-4a60-b4b9-5d22bcd19bf7] raised unexpected: HarvesterCouldNotAddBlock('0xac114aa803c4f4f8f5b36fbf27e67a04a9c54b1fad4e74e4d3173da51d8e1702',)
Traceback (most recent call last):
  File "/usr/src/app/app/tasks.py", line 110, in accumulate_block_recursive
    block = harvester.add_block(block_hash)
  File "/usr/src/app/app/processors/converters.py", line 460, in add_block
    self.process_metadata(parent_spec_version, parent_hash)
  File "/usr/src/app/app/processors/converters.py", line 201, in process_metadata
    runtime = Runtime.query(self.db_session).get(spec_version)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 959, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1069, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 282, in load_on_pk_identity
    return q.one()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3292, in one
    ret = self.one_or_none()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3261, in one_or_none
    ret = list(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3334, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3356, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3371, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3349, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1124, in connection
    execution_options=execution_options,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1130, in _connection_for_bind
    engine, execution_options
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 408, in _connection_for_bind
    self._assert_active()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 299, in _assert_active
    "This session is in 'inactive' state, due to the "
sqlalchemy.exc.InvalidRequestError: This session is in 'inactive' state, due to the SQL transaction being rolled back; no further SQL can be emitted within this transaction.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 375, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/src/app/app/tasks.py", line 70, in __call__
    return super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 632, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/app/tasks.py", line 137, in accumulate_block_recursive
    raise HarvesterCouldNotAddBlock(block_hash) from exc
app.processors.converters.HarvesterCouldNotAddBlock: 0xac114aa803c4f4f8f5b36fbf27e67a04a9c54b1fad4e74e4d3173da51d8e1702

**Comment by arjanz** [comment]
There were some updates and compatibility fixes the last week, could you try again?
