### ISSUE TITLE
[Harvester] Authentication plugin 'caching_sha2_password' is not supported

### ISSUE THREAD

**Issue by Netherdrake** [polkascan/polkascan-os#38]
Running from current polkascan-os `master`:
```
commit e22182f38430e8d851a303a1e6ca839ce8ef5563 (HEAD -> master, origin/master, origin/HEAD)
```

Command:
```
docker-compose -p test -f docker-compose.substrate-node-template.yml up --build
```

The migrations fail to run:
```
harvester-api_1      | Running migrations...
harvester-api_1      | Traceback (most recent call last):
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
harvester-api_1      |     return fn()
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
harvester-api_1      |     return _ConnectionFairy._checkout(self)
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
harvester-api_1      |     fairy = _ConnectionRecord.checkout(pool)
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
harvester-api_1      |     rec = pool._do_get()
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
harvester-api_1      |     return self._create_connection()
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
harvester-api_1      |     return _ConnectionRecord(self)
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
harvester-api_1      |     self.__connect(first_connect_check=True)
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
harvester-api_1      |     connection = pool._invoke_creator(self)
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
harvester-api_1      |     return dialect.connect(*cargs, **cparams)
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 453, in connect
harvester-api_1      |     return self.dbapi.connect(*cargs, **cparams)
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/mysql/connector/__init__.py", line 179, in connect
harvester-api_1      |     return MySQLConnection(*args, **kwargs)
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/mysql/connector/connection.py", line 94, in __init__
harvester-api_1      |     self.connect(**kwargs)
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/mysql/connector/abstracts.py", line 722, in connect
harvester-api_1      |     self._open_connection()
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/mysql/connector/connection.py", line 209, in _open_connection
harvester-api_1      |     self._do_auth(self._user, self._password,
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/mysql/connector/connection.py", line 136, in _do_auth
harvester-api_1      |     packet = self._protocol.make_auth(
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/mysql/connector/protocol.py", line 99, in make_auth
harvester-api_1      |     packet += self._auth_response(client_flags, username, password,
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/mysql/connector/protocol.py", line 58, in _auth_response
harvester-api_1      |     auth = get_auth_plugin(auth_plugin)(
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/mysql/connector/authentication.py", line 190, in get_auth_plugin
harvester-api_1      |     raise errors.NotSupportedError(
harvester-api_1      | mysql.connector.errors.NotSupportedError: Authentication plugin 'caching_sha2_password' is not supported
harvester-api_1      |
harvester-api_1      | The above exception was the direct cause of the following exception:
harvester-api_1      |
harvester-api_1      | Traceback (most recent call last):
harvester-api_1      |   File "/usr/local/bin/alembic", line 8, in <module>
harvester-api_1      |     sys.exit(main())
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/alembic/config.py", line 540, in main
harvester-api_1      |     CommandLine(prog=prog).main(argv=argv)
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/alembic/config.py", line 534, in main
harvester-api_1      |     self.run_cmd(cfg, options)
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/alembic/config.py", line 511, in run_cmd
harvester-api_1      |     fn(
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/alembic/command.py", line 279, in upgrade
harvester-api_1      |     script.run_env()
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/alembic/script/base.py", line 475, in run_env
harvester-api_1      |     util.load_python_file(self.dir, "env.py")
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 98, in load_python_file
harvester-api_1      |     module = load_module_py(module_id, path)
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/alembic/util/compat.py", line 174, in load_module_py
harvester-api_1      |     spec.loader.exec_module(module)
harvester-api_1      |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
harvester-api_1      |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
harvester-api_1      |   File "app/db/env.py", line 89, in <module>
harvester-api_1      |     run_migrations_online()
harvester-api_1      |   File "app/db/env.py", line 77, in run_migrations_online
harvester-api_1      |     with connectable.connect() as connection:
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2206, in connect
harvester-api_1      |     return self._connection_cls(self, **kwargs)
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 103, in __init__
harvester-api_1      |     else engine.raw_connection()
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2305, in raw_connection
harvester-api_1      |     return self._wrap_pool_connect(
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2278, in _wrap_pool_connect
harvester-api_1      |     Connection._handle_dbapi_exception_noconnection(
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1544, in _handle_dbapi_exception_noconnection
harvester-api_1      |     util.raise_from_cause(sqlalchemy_exception, exc_info)
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
harvester-api_1      |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
harvester-api_1      |     raise value.with_traceback(tb)
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
harvester-api_1      |     return fn()
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 303, in unique_connection
harvester-api_1      |     return _ConnectionFairy._checkout(self)
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
harvester-api_1      |     fairy = _ConnectionRecord.checkout(pool)
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
harvester-api_1      |     rec = pool._do_get()
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 238, in _do_get
harvester-api_1      |     return self._create_connection()
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
harvester-api_1      |     return _ConnectionRecord(self)
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
harvester-api_1      |     self.__connect(first_connect_check=True)
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
harvester-api_1      |     connection = pool._invoke_creator(self)
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
harvester-api_1      |     return dialect.connect(*cargs, **cparams)
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 453, in connect
harvester-api_1      |     return self.dbapi.connect(*cargs, **cparams)
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/mysql/connector/__init__.py", line 179, in connect
harvester-api_1      |     return MySQLConnection(*args, **kwargs)
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/mysql/connector/connection.py", line 94, in __init__
harvester-api_1      |     self.connect(**kwargs)
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/mysql/connector/abstracts.py", line 722, in connect
harvester-api_1      |     self._open_connection()
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/mysql/connector/connection.py", line 209, in _open_connection
harvester-api_1      |     self._do_auth(self._user, self._password,
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/mysql/connector/connection.py", line 136, in _do_auth
harvester-api_1      |     packet = self._protocol.make_auth(
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/mysql/connector/protocol.py", line 99, in make_auth
harvester-api_1      |     packet += self._auth_response(client_flags, username, password,
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/mysql/connector/protocol.py", line 58, in _auth_response
harvester-api_1      |     auth = get_auth_plugin(auth_plugin)(
harvester-api_1      |   File "/usr/local/lib/python3.8/site-packages/mysql/connector/authentication.py", line 190, in get_auth_plugin
harvester-api_1      |     raise errors.NotSupportedError(
harvester-api_1      | sqlalchemy.exc.NotSupportedError: (mysql.connector.errors.NotSupportedError) Authentication plugin 'caching_sha2_password' is not supported
```

**Comment by Netherdrake** [comment]
Fixed it by deleting conflicting dependency:
```
~/G/P/p/harvester % git diff
diff --git a/requirements.txt b/requirements.txt
index fd6330e..e878464 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -18,7 +18,6 @@ Mako==1.0.8
 MarkupSafe==1.1.1
 meinheld==1.0.2
 more-itertools==6.0.0
-mysql-connector==2.1.7
 mysql-connector-python==8.0.15
 packaging==19.1
 pluggy==0.9.0
```

**Comment by arjanz** [comment]
Pushed a fix, thanks for reporting! (https://github.com/polkascan/polkascan-pre-harvester/commit/7aa719f1e6a141f5e3b1b59bee3f396fad96f318)

**Comment by lovesh** [comment]
I still have this error while trying to query any endpoint in the UI

```
explorer-api_1       | Traceback (most recent call last):
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/falcon/api.py", line 244, in __call__
explorer-api_1       |     responder(req, resp, **params)
explorer-api_1       |   File "/usr/src/app/app/resources/base.py", line 109, in on_get
explorer-api_1       |     cache_response = self.process_get_response(req, resp, **kwargs)
explorer-api_1       |   File "/usr/src/app/app/resources/base.py", line 141, in process_get_response
explorer-api_1       |     items = self.apply_paging(items, req.params)
explorer-api_1       |   File "/usr/src/app/app/resources/base.py", line 136, in apply_paging
explorer-api_1       |     return query[page * page_size: page * page_size + page_size]
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3018, in __getitem__
explorer-api_1       |     return list(res)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3334, in __iter__
explorer-api_1       |     return self._execute_and_instances(context)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3356, in _execute_and_instances
explorer-api_1       |     querycontext, self._connection_from_session, close_with_result=True
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3371, in _get_bind_args
explorer-api_1       |     mapper=self._bind_mapper(), clause=querycontext.statement, **kw
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3349, in _connection_from_session
explorer-api_1       |     conn = self.session.connection(**kw)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1124, in connection
explorer-api_1       |     execution_options=execution_options,
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1130, in _connection_for_bind
explorer-api_1       |     engine, execution_options
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 431, in _connection_for_bind
explorer-api_1       |     conn = bind._contextual_connect()
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2239, in _contextual_connect
explorer-api_1       |     self._wrap_pool_connect(self.pool.connect, None),
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2279, in _wrap_pool_connect
explorer-api_1       |     e, dialect, self
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1544, in _handle_dbapi_exception_noconnection
explorer-api_1       |     util.raise_from_cause(sqlalchemy_exception, exc_info)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
explorer-api_1       |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
explorer-api_1       |     raise value.with_traceback(tb)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
explorer-api_1       |     return fn()
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 363, in connect
explorer-api_1       |     return _ConnectionFairy._checkout(self)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
explorer-api_1       |     fairy = _ConnectionRecord.checkout(pool)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
explorer-api_1       |     rec = pool._do_get()
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
explorer-api_1       |     self._dec_overflow()
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
explorer-api_1       |     compat.reraise(exc_type, exc_value, exc_tb)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
explorer-api_1       |     raise value
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
explorer-api_1       |     return self._create_connection()
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
explorer-api_1       |     return _ConnectionRecord(self)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
explorer-api_1       |     self.__connect(first_connect_check=True)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
explorer-api_1       |     connection = pool._invoke_creator(self)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
explorer-api_1       |     return dialect.connect(*cargs, **cparams)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 453, in connect
explorer-api_1       |     return self.dbapi.connect(*cargs, **cparams)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/mysql/connector/__init__.py", line 179, in connect
explorer-api_1       |     return MySQLConnection(*args, **kwargs)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection.py", line 94, in __init__
explorer-api_1       |     self.connect(**kwargs)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/mysql/connector/abstracts.py", line 722, in connect
explorer-api_1       |     self._open_connection()
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection.py", line 211, in _open_connection
explorer-api_1       |     self._ssl)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection.py", line 141, in _do_auth
explorer-api_1       |     auth_plugin=self._auth_plugin)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/mysql/connector/protocol.py", line 102, in make_auth
explorer-api_1       |     auth_data, ssl_enabled)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/mysql/connector/protocol.py", line 58, in _auth_response
explorer-api_1       |     auth = get_auth_plugin(auth_plugin)(
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/mysql/connector/authentication.py", line 191, in get_auth_plugin
explorer-api_1       |     "Authentication plugin '{0}' is not supported".format(plugin_name))
explorer-api_1       | sqlalchemy.exc.NotSupportedError: (mysql.connector.errors.NotSupportedError) Authentication plugin 'caching_sha2_password' is not supported
explorer-api_1       | (Background on this error at: http://sqlalche.me/e/tw8g)
explorer-api_1       | 
```
