### ISSUE TITLE
Harvester can't parse the block

### ISSUE THREAD

**Issue by pgolovkin** [polkascan/polkascan-os#45]
Harvester can't parse the block.
I'm getting error

AttributeError: 'GenericAccountId' object has no attribute 'account_length'

Full trance
Traceback (most recent call last):
  File "/usr/src/app/app/tasks.py", line 120, in accumulate_block_recursive
    block = harvester.add_block(block_hash)
  File "/usr/src/app/app/processors/converters.py", line 617, in add_block
    extrinsic_data = extrinsics_decoder.decode()
  File "/usr/src/app/py-scale-codec/scalecodec/base.py", line 382, in decode
    self.value = self.process()
  File "/usr/src/app/py-scale-codec/scalecodec/block.py", line 178, in process
    result['account_id'] = self.address.account_id
AttributeError: 'GenericAccountId' object has no attribute 'account_length'

**Comment by arjanz** [comment]
I'm guessing the type mappings for `Address` and `LookupSource` are incorrect, it should be either `GenericAddress`, `AccountIdAddress` or `MultiAddress`.

e.g.
```
...
"types": {
        "Address": "GenericAddress",
        "LookupSource": "GenericAddress",
...
```

**Comment by pgolovkin** [comment]
Thanks. Now I'm getting the error 

Traceback (most recent call last):
  File "/usr/src/app/app/tasks.py", line 120, in accumulate_block_recursive
    block = harvester.add_block(block_hash)
  File "/usr/src/app/app/processors/converters.py", line 490, in add_block
    self.process_metadata(parent_spec_version, parent_hash)
  File "/usr/src/app/app/processors/converters.py", line 219, in process_metadata
    runtime = Runtime.query(self.db_session).get(spec_version)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 959, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 1069, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 282, in load_on_pk_identity
    return q.one()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3292, in one
    ret = self.one_or_none()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3261, in one_or_none
    ret = list(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3334, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3355, in _execute_and_instances
    conn = self._get_bind_args(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3370, in _get_bind_args
    return fn(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3349, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1121, in connection
    return self._connection_for_bind(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1129, in _connection_for_bind
    return self.transaction._connection_for_bind(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 408, in _connection_for_bind
    self._assert_active()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 298, in _assert_active
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This session is in 'inactive' state, due to the SQL transaction being rolled back; no further SQL can be emitted within this transaction.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/src/app/app/tasks.py", line 70, in __call__
    return super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/app/tasks.py", line 147, in accumulate_block_recursive
    raise HarvesterCouldNotAddBlock(block_hash) from exc
app.processors.converters.HarvesterCouldNotAddBlock: 0x51532b523502972354223b51391c51420e340873b302f10bc8fbcda930227d85
