### ISSUE TITLE
Substrate 3 support

### ISSUE THREAD

**Issue by pgolovkin** [polkascan/polkascan-os#46]
Hello!
Does polkascan-os support substrate 3? 
I'm getting error 
```
Traceback (most recent call last):
  File "/usr/src/app/app/tasks.py", line 120, in accumulate_block_recursive
    block = harvester.add_block(block_hash)
  File "/usr/src/app/app/processors/converters.py", line 705, in add_block
    block_processor.accumulation_hook(self.db_session)
  File "/usr/src/app/app/processors/block.py", line 65, in accumulation_hook
    ScaleBytes(bytearray.fromhex(log.data['value']['data'].replace('0x', '')))
AttributeError: 'dict' object has no attribute 'replace'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/src/app/app/tasks.py", line 70, in __call__
    return super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/app/tasks.py", line 147, in accumulate_block_recursive
    raise HarvesterCouldNotAddBlock(block_hash) from exc
app.processors.converters.HarvesterCouldNotAddBlock: 0x898031f6fdbec020894ad79f4f6b703ccadfc1223675c0e2aede4ff8526b346f
```

and

````
Traceback (most recent call last):
  File "/usr/src/app/app/tasks.py", line 120, in accumulate_block_recursive
    block = harvester.add_block(block_hash)
  File "/usr/src/app/app/processors/converters.py", line 705, in add_block
    block_processor.accumulation_hook(self.db_session)
  File "/usr/src/app/app/processors/block.py", line 503, in accumulation_hook
    account_id=search_index[0]
  File "/usr/src/app/app/processors/converters.py", line 1064, in create_balance_snapshot
    account_info_data = self.substrate.get_runtime_state(
  File "/usr/src/app/py-substrate-interface/substrateinterface/base.py", line 1347, in get_runtime_state
    obj = self.query(module, storage_function, params=params, block_hash=block_hash)
  File "/usr/src/app/py-substrate-interface/substrateinterface/base.py", line 1339, in query
    obj.decode()
  File "/usr/src/app/py-scale-codec/scalecodec/base.py", line 382, in decode
    self.value = self.process()
  File "/usr/src/app/py-scale-codec/scalecodec/types.py", line 461, in process
    result[key] = self.process_type(data_type, metadata=self.metadata).value
  File "/usr/src/app/py-scale-codec/scalecodec/base.py", line 442, in process_type
    obj.decode(check_remaining=False)
  File "/usr/src/app/py-scale-codec/scalecodec/base.py", line 382, in decode
    self.value = self.process()
  File "/usr/src/app/py-scale-codec/scalecodec/types.py", line 461, in process
    result[key] = self.process_type(data_type, metadata=self.metadata).value
  File "/usr/src/app/py-scale-codec/scalecodec/base.py", line 442, in process_type
    obj.decode(check_remaining=False)
  File "/usr/src/app/py-scale-codec/scalecodec/base.py", line 389, in decode
    raise RemainingScaleBytesNotEmptyException(
scalecodec.exceptions.RemainingScaleBytesNotEmptyException: No more bytes available (offset: 80 / length: 76)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/src/app/app/tasks.py", line 70, in __call__
    return super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/app/tasks.py", line 147, in accumulate_block_recursive
    raise HarvesterCouldNotAddBlock(block_hash) from exc
app.processors.converters.HarvesterCouldNotAddBlock: 0x2058b770314fda4a45be87dbf1fcb172419429371851977736c4578401fecbae
```

**Comment by lovesh** [comment]
Got similar error
```
ERROR/ForkPoolWorker-4] Task app.tasks.accumulate_block_recursive[a86f8e2e-37f3-4d21-bf3b-fd7497db23f9] raised unexpected: HarvesterCouldNotAddBlock('0x62462a8ea4955ca2221e6604e53557cfd25acfb2215fe3d1e79d880ff82b4d03')
harvester-worker_1   | Traceback (most recent call last):
harvester-worker_1   |   File "/usr/src/app/app/tasks.py", line 120, in accumulate_block_recursive
harvester-worker_1   |     block = harvester.add_block(block_hash)
harvester-worker_1   |   File "/usr/src/app/app/processors/converters.py", line 540, in add_block
harvester-worker_1   |     events_decoder = self.substrate.get_block_events(block_hash, self.metadata_store[parent_spec_version])
harvester-worker_1   |   File "/usr/src/app/py-substrate-interface/substrateinterface/base.py", line 882, in get_block_events
harvester-worker_1   |     events_decoder.decode()
harvester-worker_1   |   File "/usr/src/app/py-scale-codec/scalecodec/base.py", line 382, in decode
harvester-worker_1   |     self.value = self.process()
harvester-worker_1   |   File "/usr/src/app/py-scale-codec/scalecodec/block.py", line 310, in process
harvester-worker_1   |     element = self.process_type('EventRecord', metadata=self.metadata)
harvester-worker_1   |   File "/usr/src/app/py-scale-codec/scalecodec/base.py", line 442, in process_type
harvester-worker_1   |     obj.decode(check_remaining=False)
harvester-worker_1   |   File "/usr/src/app/py-scale-codec/scalecodec/base.py", line 382, in decode
harvester-worker_1   |     self.value = self.process()
harvester-worker_1   |   File "/usr/src/app/py-scale-codec/scalecodec/block.py", line 402, in process
harvester-worker_1   |     self.topics = self.process_type('Vec<Hash>').value
harvester-worker_1   |   File "/usr/src/app/py-scale-codec/scalecodec/base.py", line 442, in process_type
harvester-worker_1   |     obj.decode(check_remaining=False)
harvester-worker_1   |   File "/usr/src/app/py-scale-codec/scalecodec/base.py", line 382, in decode
harvester-worker_1   |     self.value = self.process()
harvester-worker_1   |   File "/usr/src/app/py-scale-codec/scalecodec/types.py", line 811, in process
harvester-worker_1   |     element = self.process_type(self.sub_type, metadata=self.metadata)
harvester-worker_1   |   File "/usr/src/app/py-scale-codec/scalecodec/base.py", line 442, in process_type
harvester-worker_1   |     obj.decode(check_remaining=False)
harvester-worker_1   |   File "/usr/src/app/py-scale-codec/scalecodec/base.py", line 389, in decode
harvester-worker_1   |     raise RemainingScaleBytesNotEmptyException(
harvester-worker_1   | scalecodec.exceptions.RemainingScaleBytesNotEmptyException: No more bytes available (offset: 118 / length: 111)
harvester-worker_1   | 
harvester-worker_1   | The above exception was the direct cause of the following exception:
harvester-worker_1   | 
harvester-worker_1   | Traceback (most recent call last):
harvester-worker_1   |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
harvester-worker_1   |     R = retval = fun(*args, **kwargs)
harvester-worker_1   |   File "/usr/src/app/app/tasks.py", line 70, in __call__
harvester-worker_1   |     return super().__call__(*args, **kwargs)
harvester-worker_1   |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 648, in __protected_call__
harvester-worker_1   |     return self.run(*args, **kwargs)
harvester-worker_1   |   File "/usr/src/app/app/tasks.py", line 147, in accumulate_block_recursive
harvester-worker_1   |     raise HarvesterCouldNotAddBlock(block_hash) from exc
```

**Comment by pgolovkin** [comment]
Fixed with py-scale-codec update
