### ISSUE TITLE
SQLAlchemy Error

### ISSUE THREAD

**Issue by Alexandr1227** [polkascan/polkascan-os#48]
I've got this error whenever I am build with this command. "docker-compose -p kusama -f docker-compose.kusama-full.yml up --build"
Why does this have SQLAlchemy Error and how can I fix it??
In the browser, so many 500 Errors are appeared on console log and I think this is a MySQL connection Error.
I hope you please help me. Then I am so grateful.
thanks

explorer-api_1       | Traceback (most recent call last):
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/falcon/api.py", line 244, in __call__
explorer-api_1       |     responder(req, resp, **params)
explorer-api_1       |   File "/usr/src/app/app/resources/base.py", line 109, in on_get
explorer-api_1       |     cache_response = self.process_get_response(req, resp, **kwargs)
explorer-api_1       |   File "/usr/src/app/app/resources/base.py", line 141, in process_get_response
explorer-api_1       |     items = self.apply_paging(items, req.params)
explorer-api_1       |   File "/usr/src/app/app/resources/base.py", line 136, in apply_paging
explorer-api_1       |     return query[page * page_size: page * page_size + page_size]
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3018, in __getitem__
explorer-api_1       |     return list(res)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3334, in __iter__
explorer-api_1       |     return self._execute_and_instances(context)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3356, in _execute_and_instances
explorer-api_1       |     querycontext, self._connection_from_session, close_with_result=True
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3371, in _get_bind_args
explorer-api_1       |     mapper=self._bind_mapper(), clause=querycontext.statement, **kw
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3349, in _connection_from_session
explorer-api_1       |     conn = self.session.connection(**kw)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1124, in connection
explorer-api_1       |     execution_options=execution_options,
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1130, in _connection_for_bind
explorer-api_1       |     engine, execution_options
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 431, in _connection_for_bind
explorer-api_1       |     conn = bind._contextual_connect()
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2239, in _contextual_connect
explorer-api_1       |     self._wrap_pool_connect(self.pool.connect, None),
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2279, in _wrap_pool_connect
explorer-api_1       |     e, dialect, self
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1544, in _handle_dbapi_exception_noconnection
explorer-api_1       |     util.raise_from_cause(sqlalchemy_exception, exc_info)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
explorer-api_1       |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
explorer-api_1       |     raise value.with_traceback(tb)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
explorer-api_1       |     return fn()
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 363, in connect
explorer-api_1       |     return _ConnectionFairy._checkout(self)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
explorer-api_1       |     fairy = _ConnectionRecord.checkout(pool)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
explorer-api_1       |     rec = pool._do_get()
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
explorer-api_1       |     self._dec_overflow()
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
explorer-api_1       |     compat.reraise(exc_type, exc_value, exc_tb)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
explorer-api_1       |     raise value
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
explorer-api_1       |     return self._create_connection()
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
explorer-api_1       |     return _ConnectionRecord(self)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
explorer-api_1       |     self.__connect(first_connect_check=True)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
explorer-api_1       |     connection = pool._invoke_creator(self)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
explorer-api_1       |     return dialect.connect(*cargs, **cparams)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 453, in connect
explorer-api_1       |     return self.dbapi.connect(*cargs, **cparams)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/mysql/connector/__init__.py", line 179, in connect
explorer-api_1       |     return MySQLConnection(*args, **kwargs)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection.py", line 94, in __init__
explorer-api_1       |     self.connect(**kwargs)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/mysql/connector/abstracts.py", line 722, in connect
explorer-api_1       |     self._open_connection()
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection.py", line 211, in _open_connection
explorer-api_1       |     self._ssl)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/mysql/connector/connection.py", line 141, in _do_auth
explorer-api_1       |     auth_plugin=self._auth_plugin)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/mysql/connector/protocol.py", line 102, in make_auth
explorer-api_1       |     auth_data, ssl_enabled)
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/mysql/connector/protocol.py", line 58, in _auth_response
explorer-api_1       |     auth = get_auth_plugin(auth_plugin)(
explorer-api_1       |   File "/usr/local/lib/python3.6/site-packages/mysql/connector/authentication.py", line 191, in get_auth_plugin
explorer-api_1       |     "Authentication plugin '{0}' is not supported".format(plugin_name))
explorer-api_1       | sqlalchemy.exc.NotSupportedError: (mysql.connector.errors.NotSupportedError) Authentication plugin 'caching_sha2_password' is not supported
explorer-api_1       | (Background on this error at: http://sqlalche.me/e/tw8g)
explorer-api_1       |

**Comment by Alexandr1227** [comment]
no response from the other developers
